export type DEPLOYED_TYPE = {
  Stake1Proxy_ADDRESS: string;
  TON_ADDRESS: string;
  DOC_ADDRESS: string;
  TOS_ADDRESS: string;
  WTON_ADDRESS: string;
  DepositManager_ADDRESS: string;
  SeigManager_ADDRESS: string;
  SwapProxy_ADDRESS: string;
  TokamakLayer2_ADDRESS: string;
  Airdrop_ADDRESS: string;
  LockTOS_ADDRESS: string;
  UniswapStaking_Address: string;
  UniswapStaker_Address: string;
  NPM_Address: string;
  BasePool_Address: string;
  DOCPool_Address: string;
  StakeTonControl_ADDRESS: string;
  LockTOSProxy_ADDRESS:string;
  DividendPool_ADDRESS: string;
  DividendPoolProxy_ADDRESS: string;
  PublicSale_ADDRESS: string;
};
